### ISSUE TITLE
Make single visual studio solution at base of git repository?

### ISSUE THREAD

**Issue by blobjim** [huskyroboticsteam/2017-18#13]
I'm new to Visual Studio and C#, but it seems to me like we only need a single .sln file for the entire repository, since solutions are supposed to be containers for projects, and projects are supposed to be independent executables. Each of the subsections can have a C# project possibly containing other C# projects, but it seems unnecessary to have an sln for every subsection. Thoughts?

**Comment by CaiB** [comment]
This is what we do for Science, and it works well for us.

**Comment by CaiB** [comment]
Hang on, I misinterpreted this, sorry.
I meant in Science we have a solution containing both our Base and Rover sides.

I think it makes sense to keep subsystems (Arm, Science, etc) in separate solutions, but to have any subcomponents as projects in that repository.

Putting everything together would probably slow down things considerably for everyone, when most people won't ever need to access another subsystem's project.

**Comment by blobjim** [comment]
Sounds good.
