### ISSUE TITLE
'SendPackets' fails when 'Endpoint' is null

### ISSUE THREAD

**Issue by LouYu2015** [huskyroboticsteam/2017-18#7]
Can be reproduced by the following program.

Client side:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Scarlet.Communications;
using Scarlet.Utilities;

namespace ConsoleAppClient
{
    class Program
    {
        static void Main(string[] args)
        {
            Client.Start("127.0.0.1", 2000, 2001, "MyClient");
            System.Threading.Thread.Sleep(3000);
            for (int i = 0; i < 20; i++)
            {
                Packet MyPack = new Packet(new Message(0xc3, UtilData.ToBytes("Hello, World!")), false);
                Client.Send(MyPack);
                //System.Threading.Thread.Sleep(500);
            }
        }
    }
}

```
Server side:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Scarlet.Communications;
using Scarlet.Utilities;

class Program
{
    static void Main(string[] args)
    {
        Server.Start(2000, 2001);
        Parse.SetParseHandler(0xc3, ReceiveMessage);
    }

    static void ReceiveMessage(Message message)
    {
        Console.WriteLine("Got message");
        Console.WriteLine(UtilData.ToString(message.Payload));
    }
}
```

Stack trace:

> Unhandled Exception: System.ArgumentNullException: Value cannot be null.
> Parameter name: str
>    at System.String.Copy(String str)
>    at Scarlet.Communications.Packet.Clone()
>    at Scarlet.Communications.Client.SendPackets()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

Problem:

`Communications.Packet.Clone` fails to copy `Endpoint` when it is null.

Possible solution:

Change `Clone.Endpoint = string.Copy(this.Endpoint);` to `Clone.Endpoint = this.Endpoint?
 string.Copy(this.Endpoint) : null;`

**Comment by CaiB** [comment]
Hi there,

We encountered this issue several times today during the software workshop. We have actually already fixed it in `development`, and the fix will be included in the next release. The solution was actually to set the default endpoint for packets on the client to "Server", as otherwise it also wouldn't get sent correctly, and this also resolves this issue.

Thanks for the detailed report though!

**Comment by LouYu2015** [comment]
Yeah, your solution sounds better. BTW, that's the problem that stuck me for a long time during today's workshop...

**Comment by CaiB** [comment]
Yeah, sorry about that. It's still far from a stable release, so we appreciate your patience and reports. Hopefully we'll have a really nice library put together in a few weeks :)

**Comment by CaiB** [comment]
0.2.2 has been released, and this issue has been fixed.
